workflows:
  expo-android-apk:
    name: Expo Android APK

    environment:
      groups:
        - expo

    scripts:
      - npm install
      - npm install -g eas-cli
      - eas build --platform android --profile preview --non-interactive

    artifacts:
      - "*.apk"
